### ISSUE TITLE
turn on/off individual alerts

### ISSUE THREAD

**Issue by nicolasochem** [kukabi/polkadot-kusama-1kv-telegram-bot#1]
The ryabina bot lets you turn alerts on and off individually. It would be good to have this here (block authorship for example, or reward payouts, is too noisy).

**Comment by kukabi** [comment]
@nicolasochem good idea, thanks. Definitely would be great to have the alerts configurable as in the ryabina bot, and configuration UI there is really smooth. I'll work on it.

**Comment by kukabi** [comment]
v1.1.0 (fd5b549) partially helps reduce the noisiness, more to come around this topic though.

**Comment by kukabi** [comment]
`/settings` in the current `v1.3.0` release enables the user to turn off or configure block authorship and unclaimed payout notifications.

![Screen Shot 2021-04-17 at 18 57 25](https://user-images.githubusercontent.com/2969501/115118974-c6996680-9fae-11eb-8a8c-8cb37876ffa8.png)
