### ISSUE TITLE
watch for chilling events on-chain

### ISSUE THREAD

**Issue by nicolasochem** [kukabi/polkadot-kusama-1kv-telegram-bot#2]
The offline alert relies on the 1kv backend, but it is sometimes glitchy. It would be good to alert for the actual offline events from the chain (chilling).

**Comment by kukabi** [comment]
Thanks for this too Nicolas! I agree that chain events would be more reliable. I'll go through the RPC docs and see how much of the data I can fetch from there.

**Comment by nicolasochem** [comment]
excellent, thank you

**Comment by kukabi** [comment]
@nicolasochem cheers:)
