### ISSUE TITLE
better alerts for unclaimed rewards

### ISSUE THREAD

**Issue by nicolasochem** [kukabi/polkadot-kusama-1kv-telegram-bot#3]
The bot warns about unpaid rewards right when the era ends. This is not useful since most probably the validator has a payout bot that fires periodically. It would be better to warn for "unpaid payouts more than 4 eras old kusama and 1 for polkadot". This gives the operator 24 hours to pay their rewards before getting alerted.

**Comment by kukabi** [comment]
Thanks @nicolasochem, I agree - and the notice sometimes is a bit too early, so when one goes to the JS app the payouts do not appear. I guess a better solution would be, as you noted, check 24h back at the end of each era. I will implement this quickly & release.

**Comment by kukabi** [comment]
Current `v1.3.0` allows for fine-grained configuration of unclaimed payout notification.

![Screen Shot 2021-04-17 at 18 54 22](https://user-images.githubusercontent.com/2969501/115118925-728e8200-9fae-11eb-9a73-e4f19d1abb49.png)
