### ISSUE TITLE
Improve nomination alerts.

### ISSUE THREAD

**Issue by kukabi** [kukabi/polkadot-kusama-1kv-telegram-bot#4]
Current nomination alerts rely on the 1KV data, a better way would be use the chain data to alert about nomination changes. Even better, a `/nominations` command that shows active and inactive nominations would be helpful.

**Comment by nicolasochem** [comment]
But only if it's optional - random nominations are super noisy.

**Comment by kukabi** [comment]
@nicolasochem yeah I'm thinking about removing the current nomination notifications, `/nominations` command should be enough. And maybe configurable notifications for nomination changes too.
