### ISSUE TITLE
DOT precision is wrong (needs to be 10 instead of 12)

### ISSUE THREAD

**Issue by antonkhvorov** [kukabi/polkadot-kusama-1kv-telegram-bot#6]
You can use RPC call to get precision of Substrate network: system.properties, e.g. for Polkadot you will get:
```
{
  ss58Format: 0,
  tokenDecimals: [
    10
  ],
  tokenSymbol: [
    DOT
  ]
}
```

This basically means that DOT decimals is 10 (while KSM is 12). Currently, the bot is configured that DOT has 12 precision, which needs to be updated to 10.

**Comment by kukabi** [comment]
Thanks a lot @antonkhvorov, I'll include this fix in the coming release.

**Comment by kukabi** [comment]
Fixed & live.
