### ISSUE TITLE
Can't get validator info with special characters in the name

### ISSUE THREAD

**Issue by novy4** [kukabi/polkadot-kusama-1kv-telegram-bot#7]
Hello

I have a chain symbol in the name of my validator. I can add it to the bot, but I can query rewards or other info about it. I get error:
⛓  Novy Validator ⛓ was not found.

Regards,
Alex

**Comment by kukabi** [comment]
Thanks much for the report @novy4! Will take a look and fix it pretty soon.

**Comment by kukabi** [comment]
Hi again @novy4, the fix for the issue is live now, please give it a try. I'm closing the issue, feel free to reopen it if the bug persists. Cheers!

**Comment by novy4** [comment]
Works great now, thanks!
